#!/bin/bash
set -e

function rm_app {
    docker rm -f ${APP} > /dev/null
    docker rm -f ${CHROME} > /dev/null
    docker rm -f ${HUB} > /dev/null
}

if [ "x$1" != x ]
then
    TAG=$1
else
    TAG=foobert/gc-web
fi

echo Running tests against image ${TAG}

echo -n Starting containers.
HUB=$(docker run -d selenium/hub)
echo -n .
CHROME=$(docker run -d --link ${HUB}:hub selenium/node-chrome)
echo -n .
APP=$(docker run -d --expose 8080 ${TAG} npm start)
echo .
trap rm_app EXIT

echo "Hub    ${HUB}"
echo "Chrome ${CHROME}"
echo "App    ${APP}"

echo Sleeping 10 seconds to allow the containers to boot up
sleep 10

echo Running integration tests...
docker run --rm -t --link ${APP}:APP --link ${HUB}:hub ${TAG} node_modules/.bin/mocha

echo All passed!
