#!/bin/bash
set -e

function rm_db {
    docker rm -f ${DB}
}

function rm_app {
    rm_db
    docker logs ${APP}
    docker rm -f ${APP}
}
if [ "x$1" != x ]
then
    TAG=$1
else
    TAG=foobert/gc-storage
fi

echo Running tests against image ${TAG}

DB=$(docker run -d postgres)
echo Using temporary DB ${DB}
trap rm_db EXIT

# unit test
echo Running unit tests
docker run --rm -t --link ${DB}:DB ${TAG} node_modules/.bin/mocha test/unit\*

# start app for integration testing
APP=$(docker run -d -e DEBUG=gc:* --link ${DB}:DB --publish 8081:8081 ${TAG} npm start)
echo Using temporary APP ${APP}
trap rm_app EXIT

# run integration tests against the app
echo Running integration tests
docker run --rm -t --link ${DB}:DB --link ${APP}:APP ${TAG} node_modules/.bin/mocha test/integration\*

echo All passed!
