#!/bin/bash
set -e

function rm_db {
    docker rm -f ${DB}
}

function rm_app {
    docker rm -f ${APP}
}
if [ $1 ]
then
    TAG=$1
else
    TAG=foobert/gc-storage
fi

echo Running tests against image ${TAG}

DB=$(docker run -d postgres)
trap rm_db EXIT

# unit est
docker run --rm -t --link ${DB}:DB ${TAG} node_modules/.bin/mocha test/unit\*

# start app for integration testing
APP=$(docker run -d --link ${DB}:DB ${TAG})
trap rm_app EXIT

# run integration tests against the app
docker run --rm -t --link ${DB}:DB --link ${APP}:APP ${TAG} node_modules/.bin/mocha test/integration\*
